### ISSUE TITLE
InfluxDB Cluster PVC[meta and data], Can be created in AWS EFS / NFS storage framework !!

### ISSUE THREAD

**Issue by MohamedShaj** [chengshiwen/influxdb-cluster#30]
InfluxDB Cluster PVC, Can be created in AWS EFS / NFS storage framework !!

I can see in AWS GP2 storage class is recommended, but for the High Availability of the storage , just checking the alternative storage like NFS OR AWS EFS

Would the current cluster helm charts/manifest support the NFS/ EFS ??  or extra changes to be made in manifest? to get worked

influx cluster helm charts - https://github.com/influxtsdb/helm-charts/tree/master/charts/influxdb-cluster
Already NFS discussions -  https://github.com/influxdata/influxdb/issues/9047

**Comment by chengshiwen** [comment]
@MohamedShaj [InfluxDB Cluster](https://github.com/chengshiwen/influxdb-cluster) is an alternative to [InfluxDB Enterprise](https://docs.influxdata.com/enterprise_influxdb/v1.8/concepts/glossary/) and supports high availability (For high availability, installations must have at least two data nodes. The number of data nodes in your cluster must be the same as your highest replication factor. Any replication factor greater than two gives you additional fault tolerance and query capacity within the cluster.).

**So NFS/EFS is not required**, because the storage of each data node is completely independent and does not require network sharing. For details, please refer to [the official documentation](https://docs.influxdata.com/enterprise_influxdb/v1.8/).

For the influx cluster helm chart, you just modify the configuration items like `storageClass` and `size` in [values.yaml](https://github.com/influxtsdb/helm-charts/blob/master/charts/influxdb-cluster/values.yaml). So you need to request your storage provider.

```yaml
  persistence:
    enabled: true
    ## A manually managed Persistent Volume and Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:
    ## influxdb data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: "alicloud-disk-available"
    annotations: {}
    accessMode: ReadWriteOnce
    size: 25Gi
```
