### ISSUE TITLE
How to mount correctly?

### ISSUE THREAD

**Issue by sam30606** [chengshiwen/influxdb-cluster#33]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Operating System: Ubuntu 22.04.3 LTS
Docker Version:    24.0.6
Meta Image: 1.8.10-c1.1.2-meta
Data Image:  1.8.10-c1.1.2-data
Architecture: x86_64
__Steps to reproduce:__
docker-compoose.yml
``` 
version: "3.5"

services:
  influxdb-meta-01:
    image: chengshiwen/influxdb:1.8.10-c1.1.2-meta
    container_name: influxdb-meta-01
    restart: unless-stopped
    networks:
      - influxdb-cluster
    volumes:
      - ./configs/influxdb-meta.conf/:/etc/influxdb/influxdb-meta.conf
      - ./influxdb-meta-01/etc/influxdb/:/etc/influxdb/
      - ./influxdb-meta-01/var/lib/influxdb/:/var/lib/influxdb

  influxdb-meta-02:
    image: chengshiwen/influxdb:1.8.10-c1.1.2-meta
    container_name: influxdb-meta-02
    restart: unless-stopped
    networks:
      - influxdb-cluster
    volumes:
      - ./configs/influxdb-meta.conf/:/etc/influxdb/influxdb-meta.conf
      - ./influxdb-meta-02/etc/influxdb/:/etc/influxdb/
      - ./influxdb-meta-02/var/lib/influxdb/:/var/lib/influxdb

  influxdb-meta-03:
    image: chengshiwen/influxdb:1.8.10-c1.1.2-meta
    container_name: influxdb-meta-03
    restart: unless-stopped
    networks:
      - influxdb-cluster
    volumes:
      - ./configs/influxdb-meta.conf/:/etc/influxdb/influxdb-meta.conf
      - ./influxdb-meta-03/etc/influxdb/:/etc/influxdb/
      - ./influxdb-meta-03/var/lib/influxdb/:/var/lib/influxdb

  influxdb-data-01:
    image: chengshiwen/influxdb:1.8.10-c1.1.2-data
    container_name: influxdb-data-01
    ports:
      - 8186:8086
    restart: unless-stopped
    networks:
      - influxdb-cluster
    volumes:
      - ./configs/influxdb.conf/:/etc/influxdb/influxdb.conf
      - ./influxdb-data-01/etc/influxdb/:/etc/influxdb/
      - ./influxdb-data-01/var/lib/influxdb:/var/lib/influxdb

  influxdb-data-02:
    image: chengshiwen/influxdb:1.8.10-c1.1.2-data
    container_name: influxdb-data-02
    ports:
      - 8286:8086
    restart: unless-stopped
    networks:
      - influxdb-cluster
    volumes:
      - ./configs/influxdb.conf/:/etc/influxdb/influxdb.conf
      - ./influxdb-data-02/etc/influxdb/:/etc/influxdb/
      - ./influxdb-data-02/var/lib/influxdb:/var/lib/influxdb
```
1. [First Step]
```
docker compose up -d
docker exec -it influxdb-meta-01 bash
influxd-ctl add-meta influxdb-meta-01:8091
influxd-ctl add-meta influxdb-meta-02:8091
influxd-ctl add-meta influxdb-meta-03:8091
influxd-ctl add-data influxdb-data-01:8088
influxd-ctl add-data influxdb-data-02:8088
```
2. [Second Step]
```
docker compose down
```
3. [and so on...]
Compose up with previus data.
```
docker compose up -d
```
__Expected behavior:__ [What you expected to happen]

Influxdb cluster will working perfectly without error.

__Actual behavior:__ [What actually happened]

In container influxdb-meta-01
influxd-ctl show
```
Data Nodes
==========
ID	TCP Address	Version

Meta Nodes
==========
ID	TCP Address	Version
```

It should show like below
```
Data Nodes
==========
ID	TCP Address		Version
4	38b2aebcf853:8088	1.8.10-c1.1.2
5	279134311c56:8088	1.8.10-c1.1.2

Meta Nodes
==========
ID	TCP Address		Version
1	8b656632025b:8091	1.8.10-c1.1.2
2	377db1e4b5e7:8091	1.8.10-c1.1.2
3	5fca8e422d66:8091	1.8.10-c1.1.2
```
Then I try to add node again, the error message appear.
```
add-meta: operation exited with error: dangled meta node at "localhost:8091" already has state present, cannot add another meta node
```
Maybe my method of mount /var is incorrect?
Thank your reply!

**Comment by chengshiwen** [comment]
`./configs/influxdb-meta.conf/` and `./configs/influxdb.conf/` should be different from each other.

And the hostname like `38b2aebcf853` and `279134311c56` is an unfixed string. It is highly recommended to use a fixed hostname by setting `container_name`. After resetting the cluster and all nodes execute the command like
```
influxd-ctl -bind influxdb-meta-01:8091 add-meta influxdb-meta-01:8091
influxd-ctl -bind influxdb-meta-01:8091 add-meta influxdb-meta-02:8091
influxd-ctl -bind influxdb-meta-01:8091 add-meta influxdb-meta-03:8091
influxd-ctl -bind influxdb-meta-01:8091 add-data influxdb-data-01:8088
influxd-ctl -bind influxdb-meta-01:8091 add-data influxdb-data-02:8088
```

Please refer to [Manage Clusters](https://github.com/chengshiwen/influxdb-cluster/wiki/Manage-Clusters#--bind-hostnameport-) to learn about the option `-bind`

**Comment by sam30606** [comment]
I used the command that your provide, same problem.
After `docker compose down & up ` I tried add-meta and add-data in meta01, those are logs.
add-meta 
```
add-meta: operation exited with error: dangled meta node at "influxdb-meta-01:8091" already has state present, cannot add another meta node
```
add-data
```
add-data: operation exited with error: data node failed to contact valid meta server in list []
```

in data node
```
ts=2023-10-23T02:40:31.897305Z lvl=info msg="Failure getting snapshot" log_id=0l2agxeG000 service=metaclient server=48d8f5099c17:8091 error="Get \"http://48d8f5099c17:8091?index=0\": dial tcp: lookup 48d8f5099c17 on 127.0.0.11:53: server misbehaving"
```

**Comment by chengshiwen** [comment]
In logs from data node, you can see the error message `server=48d8f5099c17:8091 error="Get \"http://48d8f5099c17:8091?index=0\": dial tcp: lookup 48d8f5099c17 on 127.0.0.11:53: server misbehaving"`. It means your hostname is configured wrong.

You need to configure `hostname` to the fixed value I mentioned earlier in `influxdb-meta.conf` and `influxdb.conf`

**Comment by chengshiwen** [comment]
Also, please check out the [installation documentation](https://github.com/chengshiwen/influxdb-cluster/wiki#%E5%AE%89%E8%A3%85) in detail

**Comment by sam30606** [comment]
My influxdb-meta.conf and influxdb.conf were configured as follows at the top:
```
hostname="influxdb-****-0*
```
After running docker-compose down and docker-compose up, I encountered the same error, But ping the hostname is access.

**Comment by chengshiwen** [comment]
Could you provide all files including `docker-compose.yml`, `influxdb-meta.conf` and `influxdb.conf`

**Comment by sam30606** [comment]
Sure!

- docker-compose.yml

``` yml
version: "3.5"

services:
  influxdb-meta-01:
    image: chengshiwen/influxdb:1.8.10-c1.1.2-meta
    container_name: influxdb-meta-01
    restart: unless-stopped
    networks:
      - influxdb-cluster
    volumes:
      - ./influxdb-meta-01/etc/influxdb/:/etc/influxdb/
      - ./influxdb-meta-01/var/lib/influxdb/:/var/lib/influxdb

  influxdb-meta-02:
    image: chengshiwen/influxdb:1.8.10-c1.1.2-meta
    container_name: influxdb-meta-02
    restart: unless-stopped
    networks:
      - influxdb-cluster
    volumes:
      - ./influxdb-meta-02/etc/influxdb/:/etc/influxdb/
      - ./influxdb-meta-02/var/lib/influxdb/:/var/lib/influxdb

  influxdb-meta-03:
    image: chengshiwen/influxdb:1.8.10-c1.1.2-meta
    container_name: influxdb-meta-03
    restart: unless-stopped
    networks:
      - influxdb-cluster
    volumes:
      - ./influxdb-meta-03/etc/influxdb/:/etc/influxdb/
      - ./influxdb-meta-03/var/lib/influxdb/:/var/lib/influxdb

  influxdb-data-01:
    image: chengshiwen/influxdb:1.8.10-c1.1.2-data
    container_name: influxdb-data-01
    ports:
      - 8186:8086
    restart: unless-stopped
    networks:
      - influxdb-cluster
    volumes:
      - ./influxdb-data-01/etc/influxdb/:/etc/influxdb/
      - ./influxdb-data-01/var/lib/influxdb:/var/lib/influxdb

  influxdb-data-02:
    image: chengshiwen/influxdb:1.8.10-c1.1.2-data
    container_name: influxdb-data-02
    ports:
      - 8286:8086
    restart: unless-stopped
    networks:
      - influxdb-cluster
    volumes:
      - ./influxdb-data-02/etc/influxdb/:/etc/influxdb/
      - ./influxdb-data-02/var/lib/influxdb:/var/lib/influxdb

  chronograf:
    image: chronograf
    container_name: chronograf
    ports:
      - 8888:8888
    restart: unless-stopped
    networks:
      - influxdb-cluster
    volumes:
      - ./chronograf/var/lib/chronograf:/var/lib/chronograf

  kapacitor:
    image: kapacitor
    container_name: kapacitor
    ports:
      - 9092:9092
    restart: unless-stopped
    networks:
      - influxdb-cluster
    volumes:
      - ./kapacitor/etc/kapacitor:/etc/kapacitor
      - ./kapacitor/var/lib/kapacitor:/var/lib/kapacitor
      - ./kapacitor/tmp:/tmp
networks:
  influxdb-cluster:
```

- influxdb-meta.conf

``` conf
hostname="influxdb-meta-01"

[meta]
dir = "/var/lib/influxdb/meta"

```


- influxdb.conf

``` conf
hostname="influxdb-data-01"

[http]
flux-enabled = true

[meta]
dir = "/var/lib/influxdb/meta"

[data]
dir = "/var/lib/influxdb/data"
engine = "tsm1"
wal-dir = "/var/lib/influxdb/wal"

[hinted-handoff]
dir = "/var/lib/influxdb/hh"

```

**Comment by chengshiwen** [comment]
@sam30606 You forgot to configure `hostname` like `hostname: influxdb-meta-01`, and you can refer to [docker-compose.yml](https://github.com/chengshiwen/influxdb-cluster/blob/master/docker/quick/docker-compose.yml)

```yaml
  influxdb-meta-01:
    image: chengshiwen/influxdb:1.8.10-c1.1.2-meta
    container_name: influxdb-meta-01
    hostname: influxdb-meta-01
    restart: unless-stopped
    networks:
      - influxdb-cluster
```
