### ISSUE TITLE
How to preserve the state of the cluster?

### ISSUE THREAD

**Issue by masterjg** [chengshiwen/influxdb-cluster#52]
Specifically in the example compose setup. I thought that volume for /var/lib/influxdb should be enough but after stopping compose and restarting I still have to rejoin all nodes manually via:

```sh
for i in {1..3}; do
    podman compose exec influxdb-meta-1 influxd-ctl add-meta influxdb-meta-$i:8091
done
for i in {1..2}; do
    podman compose exec influxdb-meta-1 influxd-ctl add-data influxdb-data-$i:8088
done
```

Here's example compose that I've created:
```yml
x-templates:
  base: &base
    networks:
      - metrics
    restart: unless-stopped
    security_opt:
      - label:disable
    userns_mode: keep-id:uid=0,gid=0

  influxdb-data: &influxdb-data
    <<: *base
    deploy:
      resources:
        limits:
          memory: 32M
    image: chengshiwen/influxdb:1.8.11-c1.2.0-data-alpine

  influxdb-meta: &influxdb-meta
    <<: *base
    deploy:
      resources:
        limits:
          memory: 16M
    image: chengshiwen/influxdb:1.8.11-c1.2.0-meta-alpine

services:
  influxdb-data-1:
    <<: *influxdb-data
    ports:
      - 8086:8086
    volumes:
      - ./influxdb-data/data-1:/var/lib/influxdb

  influxdb-data-2:
    <<: *influxdb-data
    ports:
      - 8087:8086
    volumes:
      - ./influxdb-data/data-2:/var/lib/influxdb

  influxdb-meta-1:
    <<: *influxdb-meta
    volumes:
      - ./influxdb-data/meta-1:/var/lib/influxdb

  influxdb-meta-2:
    <<: *influxdb-meta
    volumes:
      - ./influxdb-data/meta-2:/var/lib/influxdb

  influxdb-meta-3:
    <<: *influxdb-meta
    volumes:
      - ./influxdb-data/meta-3:/var/lib/influxdb
```
