### ISSUE TITLE
docker-compose部署chronogaf疑问

### ISSUE THREAD

**Issue by zeje** [chengshiwen/influxdb-cluster#6]
https://github.com/chengshiwen/influxdb-cluster/blob/master/docker/quick/docker-compose.yml

docker-compose的部署方案
data对外开放的端口是8186，8286
meta对外不开放端口
那么，外层还需要自己加一个slb指向这两个端口吗？
还是说在docker-compose里：
加一个nginx，起8086端口，指向data节点
加一个Chronogaf指向各个节点的8086，8091端口？

**Comment by chengshiwen** [comment]
> 那么，外层还需要自己加一个slb指向这两个端口吗？

是的，直接访问8186或8286都是一样的效果，内部都会转发，考虑高可用，加上slb最好，例如nginx。influxdb本身不支持负载均衡。

> meta对外不开放端口

> docker-compose里可以开放meta对外端口，代码里提供的docker-compose.yml仅仅是一个示例

> 还是说在docker-compose里：
> 加一个nginx，起8086端口，指向data节点
> 加一个Chronogaf指向各个节点的8086，8091端口？

取决于加一个nginx的做法，是加在docker-compose里，还是脱离docker-compose
- 对于前者，就不需要暴露端口，nginx.conf里直接转发influxdb-data-01:8086和influxdb-data-02:8086就行，在docker同一网段里，无须暴露
- 对于后者，则需要转发到data对外开放的端口是8186、8286上

对于Chronogaf，道理相同，取决于Chronogaf是加在docker-compose里，还是脱离docker-compose。如果是后者，就还需暴露meta的端口

**Comment by zeje** [comment]
我尝试在docker-compose添加Chronogaf，连接到8186，但是meta服务是分开来的。
Chronogaf创建database报错了。
![image](https://user-images.githubusercontent.com/10680634/179933710-96845216-3527-434d-a8d8-7eb4d8638b8b.png)

有没有合适我们这个场景的客户端介绍？

**Comment by chengshiwen** [comment]
> 我尝试在docker-compose添加Chronogaf，连接到8186，但是meta服务是分开来的。

再暴露出meta的端口就可以，不会分开

参考这两张图:
https://github.com/chengshiwen/influxdb-cluster#clustering

架构总览:

![architecture.png](https://iili.io/Vw1XTB.png)

网络总览:

![architecture](https://docs.influxdata.com/img/enterprise/1-8-network-diagram.png)

**Comment by zeje** [comment]
``` yaml
  influxdb-cluster-chronograf:
    image: chronograf:latest
    container_name: influxdb-cluster-chronograf
    ports:
      - 8888:8888
    command: --influxdb-url=http://influxdb-data-01:8086
    restart: unless-stopped
    networks:
      - influxdb-cluster
```
好像只能这么配置，在chronograf新建一个datasource
--influxdb-url=http://influxdb-data-01:8086

chronograf 没找到能配置8091的地方
![image](https://user-images.githubusercontent.com/10680634/179992780-211f8213-d5ac-4218-a6e3-fc9b8c0f5306.png)
